### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by autonomousSpace** [YasinSonmez/Person-following-robot#1]
**ROS-MELODIC**

[  3%] Built target gazebo_msgs_generate_messages_lisp
[  3%] Built target gazebo_msgs_generate_messages_nodejs
In file included from /home/---/Desktop/person2/src/target_generation/src/target_generation_node.cpp:1:0:
/home/jawad/Desktop/person2/src/target_generation/./src/target_generation_node.h:13:10: fatal error: **leg_tracker/PersonArray.h: No such file or directory
 #include <leg_tracker/PersonArray.h>**
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
target_generation/CMakeFiles/target_generation.dir/build.make:75: recipe for target 'target_generation/CMakeFiles/target_generation.dir/src/target_generation_node.cpp.o' failed
make[2]: *** [target_generation/CMakeFiles/target_generation.dir/src/target_generation_node.cpp.o] Error 1
CMakeFiles/Makefile2:8863: recipe for target 'target_generation/CMakeFiles/target_generation.dir/all' failed
make[1]: *** [target_generation/CMakeFiles/target_generation.dir/all] Error 2
Makefile:145: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j4 -l4" failed

**Comment by autonomousSpace** [comment]
kindly reply, i need this project for my FYP

**Comment by autonomousSpace** [comment]
in the **leg_tracker/PersonArray.h** there is no  **PersonArray.h**

**Comment by YasinSonmez** [comment]
This is due to some packages needed inside others and they are not built first I guess. Try to build packages even though some of them fail a few times. For example you can use: 

catkin build -c

To continue even though some of them fail, and in the next iteration it should work.
